Frontend/FreeCourse.Web/Models/Catalog/CategoryViewModel.cs
namespace FreeCourse.Web.Models.Catalog
{
    public class CategoryViewModel
    {
        public string? Id { get; set; }
        public string Name { get; set; }
    }
}

Frontend/FreeCourse.Web/Models/Catalog/CourseCreateInput.cs
namespace FreeCourse.Web.Models.Catalog
{
    public class CourseCreateInput
    {
        public string Name { get; set; }

        public decimal Price { get; set; }

        public string Picture { get; set; }

        public DateTime CreatedDate { get; set; }

        public string UserId { get; set; }

        public FeatureViewModel feature { get; set; }


        public string CategoryId { get; set; }

        public string Description { get; set; }

    }
}

Frontend/FreeCourse.Web/Models/Catalog/CourseUpdatePut.cs
namespace FreeCourse.Web.Models.Catalog
{
    public class CourseUpdatePut
    {
        public string Id { get; set; }
        public string Name { get; set; }

        public decimal Price { get; set; }

        public string Picture { get; set; }

        public DateTime CreatedDate { get; set; }

        public string UserId { get; set; }

        public FeatureViewModel feature { get; set; }


        public string CategoryId { get; set; }

        public string Description { get; set; }
    }
}

Frontend/FreeCourse.Web/Models/Catalog/CourseViewModel.cs
namespace FreeCourse.Web.Models.Catalog
{
    public class CourseViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }

        public decimal Price { get; set; }

        public string Picture { get; set; }

        public DateTime CreatedDate { get; set; }

        public string UserId { get; set; }

        public FeatureViewModel feature { get; set; }


        public string CategoryId { get; set; }

        public string Description { get; set; }

        public CategoryViewModel category { get; set; }
    }
}

Frontend/FreeCourse.Web/Models/Catalog/FeatureViewModel.cs
namespace FreeCourse.Web.Models.Catalog
{
    public class FeatureViewModel
    {
        public int Duration { get; set; }       
    }
}

Frontend/FreeCourse.Web/Models/ClientSettings.cs
namespace FreeCourse.Web.Models
{
    public class ClientSettings
    {
        public Client WebMvcClient { get;set; }
        public Client WebClientForUser { get;set; }

    }

   public class Client
    {
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }

    }

}

Frontend/FreeCourse.Web/Models/ErrorViewModel.cs
namespace FreeCourse.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Frontend/FreeCourse.Web/Models/ServiceApiSettings.cs
namespace FreeCourse.Web.Models
{
    public class ServiceApiSettings
    {
        public string IdentityBaseURL { get; set; }
        public string GatewayURl { get; set; }

        public string PhotoStockURL { get; set; }
        public ServiceApi Catalog { get; set; }
    }

    public class ServiceApi
    { 
         public string Path { get; set;}
    
    }
}

Frontend/FreeCourse.Web/Models/SigninInput.cs
using System.ComponentModel.DataAnnotations;

namespace FreeCourse.Web.Models
{
    public class SigninInput
    {
        [Required]
        [Display(Name ="Your Email")]
        public string Username { get; set; }
        

        [Required]
        [Display(Name ="Your Password")]
        public string Password { get; set; }
        [Display(Name ="Remember me")]
        public bool IsRemember { get; set; }
    }
}

Frontend/FreeCourse.Web/Models/UserViewModel.cs
namespace FreeCourse.Web.Models
{
    public class UserViewModel
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string City { get; set; }

        public IEnumerable<string> GetUserProps()
        {
            yield return UserName;
            yield return Email;
            yield return City;

        }
        
    }
}

Frontend/FreeCourse.Web/Controllers/AuthController.cs
    using FreeCourse.Web.Models;
    using FreeCourse.Web.Services.Interface;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
    using System.Runtime.CompilerServices;

    namespace FreeCourse.Web.Controllers
    {
        public class AuthController : Controller
        {
            private readonly IIdentityService _identityservice;

            public AuthController(IIdentityService identityservice)
            {
                _identityservice = identityservice;
            }

            public IActionResult SignIn()
            {
                return View();
            }
            [HttpPost]
            public async Task<IActionResult> SignIn(SigninInput signininput)
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
              var response=await _identityservice.SignIn(signininput);
                if (!response.IsSuccessfull)
                {
                    response.Errors.ForEach(x =>
                    {
                        ModelState.AddModelError(string.Empty, x);

                    });
                    return View();
                }
         
                 return   RedirectToAction ("Index", "Home");
            }
          
            public async Task<IActionResult> Logout()
            {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await _identityservice.RevokeRefreshToken();
            return RedirectToAction(nameof(HomeController.Index), "Home");
            }

        }
    }

Frontend/FreeCourse.Web/Controllers/CourseController.cs
using FreeCourse.Shared.Services;
using FreeCourse.Web.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FreeCourse.Web.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly ICatalogService _catalogservice;
        private readonly ISharedIdentityService _sharedservice;

        public CourseController(ICatalogService catalogservice, ISharedIdentityService sharedservice)
        {
            _catalogservice = catalogservice;
            _sharedservice = sharedservice;
        }

        public async Task< IActionResult> Index()
        {
            return View(await _catalogservice.GetCourseByUserIdAsync(_sharedservice.GetUserId));  
        }

    }
}

Frontend/FreeCourse.Web/Controllers/HomeController.cs
using FreeCourse.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FreeCourse.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Frontend/FreeCourse.Web/Controllers/UserController.cs
using FreeCourse.Web.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FreeCourse.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _userService.GetUser());
        }
    }
}

Frontend/FreeCourse.Web/Views/Course/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<CourseViewModel>

<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Kurslar</h5>

                <a asp-controller="Courses" asp-action="Create" class="btn btn-primary mb-3">Kurs oluştur</a>
                @if (Model.Any())
                {
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Resim</th>
                                <th>Kurs isim</th>
                                <th>Fiyat</th>
                                <th>Süre</th>
                                <th>Kategori</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><img style="width:72px;" src="@item.Picture" class="img-thumbnail" /></td>
                                    <td>@item.Name</td>
                                    <td>@item.Price</td>
                                    <td>@item.feature.Duration</td>
                                    <td>@item.category.Name</td>
                                    <td>
                                        <a asp-controller="Courses" asp-action="Update" asp-route-id="@item.Id" class="btn btn-success btn-sm">Güncelle</a>

                                        <a asp-controller="Courses" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Sil</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        Kayıtlı kurs bulunamadı
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Frontend/FreeCourse.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Frontend/FreeCourse.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FreeCourse.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FreeCourse.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FreeCourse.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                    </ul>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="User" asp-action="Index">Profil</a></li>
                                    <li><a class="dropdown-item" asp-controller="Order" asp-action="CheckoutHistory">Ödeme geçmişim</a></li>
                                    <li><a class="dropdown-item" asp-controller="Basket" asp-action="Index">Sepet</a></li>
                                    <li><a class="dropdown-item" asp-controller="Auth" asp-action="LogOut">Çıkış</a></li>
                                </ul>
                            </li>
                        </ul>
                    }

                    else
                    {
                        <a class="nav-link text-dark" asp-controller="Auth" asp-action="SignIn" asp-area="">SignIn</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FreeCourse.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Frontend/FreeCourse.Web/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="row">

    <div class="col-md-9">

        <div class="card">
            <div class="card-body">

                <h5 class="card-title">Kullanıcı bilgileri</h5>

                <table class="table table-striped">

                    <tr>
                        <td>Kullanıcı adı</td>
                        <td>@Model.UserName</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>@Model.Email</td>
                    </tr>
                    <tr>
                        <td>Şehir</td>
                        <td>@Model.City</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>